language: node_js
node_js:
- "0.10"
- "0.12"
- "4"
sudo: false
services:
- rabbitmq
env:
- LOG_LEVEL=error
script:
- npm run lint
- npm run coverage
- npm run functional
after_success:
- npm run coveralls
